services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SONARQUBE_VERSION: ${SONARQUBE_VERSION:-26.5.0.122743-community}
        COMMUNITY_BRANCH_PLUGIN_VERSION: ${COMMUNITY_BRANCH_PLUGIN_VERSION:-26.5.0}

    image: 0niStack/sonarqube-multibranch:26.5.0

    ports:
      - "9000:9000"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
